### ISSUE TITLE
mysql_config not found

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7-docker#1]
![Capture](https://user-images.githubusercontent.com/40512816/79895012-dd24d600-83cb-11ea-9143-2f5288f00c17.PNG)

```
/usr/bin/pip install --upgrade -r requirements.txt
Collecting Django==1.10.2 (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/8a/09/46f790104abca7eb93786139d3adde9366b1afd59a77b583a1f310dc8cbd/Django-1.10.2-py2.py3-none-any.whl (6.8MB)
Collecting mysqlclient==1.3.13 (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz (90kB)
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c7UXbh/mysqlclient/setup.py", line 18, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 53, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 28, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c7UXbh/mysqlclient/
Makefile:18: recipe for target 'pip_requirements' failed
make: *** [pip_requirements] Error 1
ERROR: Service 'specify7' failed to build: The command '/bin/sh -c cd /usr/local/specify7/ &&   su - root -c "cd /usr/local/specify7/ && make all"' returned a non-zero code: 2
```

**Comment by maxpatiiuk** [comment]
It still does not work. Opened Specify/Specify7#652
