### ISSUE TITLE
No such file or directory: '/opt/Specify/specify.jar'

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7-docker#3]
![Capture](https://user-images.githubusercontent.com/40512816/80139500-2ca20800-856c-11ea-83cf-d078b9f1f80d.PNG)
```
/usr/bin/python manage.py migrate notifications
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/specify7/specifyweb/specify/models.py", line 2, in <module>
    from .check_versions import check_versions
  File "/usr/local/specify7/specifyweb/specify/check_versions.py", line 6, in <module>
    from .specify_jar import specify_jar
  File "/usr/local/specify7/specifyweb/specify/specify_jar.py", line 6, in <module>
    specify_jar = ZipFile(os.path.join(settings.SPECIFY_THICK_CLIENT, 'specify.jar'))
  File "/usr/lib/python2.7/zipfile.py", line 779, in __init__
    self.fp = open(file, modeDict[mode])
IOError: [Errno 2] No such file or directory: '/opt/Specify/specify.jar'
make: *** [django_migrations] Error 1
Makefile:21: recipe for target 'django_migrations' failed
ERROR: Service 'specify7' failed to build: The command '/bin/sh -c cd /usr/local/specify7/ &&   su - root -c "cd /usr/local/specify7/ && make all"' returned a non-zero code: 2
```

**Comment by maxpatiiuk** [comment]
Problem was that I forgot to rename `example.local_specify_settings.py` to `local_specify_settings.py`

**Comment by maxpatiiuk** [comment]
The problem was I was copying specify6 repository into specify6_thick_client instead of the client directory of installed specify6
