### ISSUE TITLE
Unable to create the django_migrations table

### ISSUE THREAD

**Issue by maxpatiiuk** [specify/specify7-docker#4]
![Capture](https://user-images.githubusercontent.com/40512816/80143156-fff0ef00-8571-11ea-977c-6741cd76002f.PNG)
```
/usr/bin/python manage.py migrate notifications
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/loader.py", line 203, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 65, in applied_migrations
    self.ensure_schema()
  File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/recorder.py", line 59, in ensure_schema
    raise MigrationSchemaMissing("Unable to create the django_migrations table (%s)" % exc)
django.db.migrations.exceptions.MigrationSchemaMissing: Unable to create the django_migrations table ((1142, "CREATE command denied to user 'master'@'localhost' for table 'django_migrations'"))
Makefile:21: recipe for target 'django_migrations' failed
make: *** [django_migrations] Error 1
ERROR: Service 'specify7' failed to build: The command '/bin/sh -c cd /usr/local/specify7/ &&   su - root -c "cd /usr/local/specify7/ && make all"' returned a non-zero code: 2
```

**Comment by maxpatiiuk** [comment]
This error was likely caused by wrong `MASTER_NAME` and `MASTER_PASSWORD` values. I will test the fix tomorrow
